### ISSUE TITLE
failing local exec still sets the id

### ISSUE THREAD

**Issue by matti** [terraform-providers/terraform-provider-null#12]
```
resource "null_resource" "test" {
  provisioner "local-exec" {
    command = "/bin/fail"
  }
}

module "some" {
  source = "../somewhere"
  arg = "${null_resource.test.id}"
}
```

`terraform apply` will fail, but since the id is set, so the next apply will "run" the module, because the dependency to `.id` is there.

**Comment by apparentlymart** [comment]
Hi @matti,

Unfortunately the interactions here are not great because provisioners are really a separate concept than resources and `null_resource` is just a pattern for using provisioners in cases where there is no specific resource to associate with.

What I'd expect to happen in this scenario is that the `null-resource.test` instance would be "tainted" by the provisioner failing, which should cause Terraform to plan to replace it on the next run. That need to replace it should then cause the id to be `<computed>`. Does that disagree with what you're seeing here? If you're able to share, it'd be helpful to see the sequence of steps you followed here including Terraform's output, to understand better what's going on.

**Comment by matti** [comment]
Actually, now when I tried to do a repro it is working as expected. Prob. was some side effect. Should always do a minimal repro case.

**Comment by matti** [comment]
here's the attempted minimal repro case for this https://github.com/matti/repro-terraform-provider-null-12 for future reference if somebody sees this again
